# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2f08483223c4458262df4e170ceb5c62cc2202b9bce6a00bd02e388bf15bdf0e17d0a3674e676b77457b1e7f2b71d74febf03cfe88915c66a8d5e741ef45d8f

test:
  secret_key_base: 687e3c3315b3ee277fbdb540580f1697b7dca59ad5f642fcb65e512dcd0c5b7d20a88b3fdfd18a48767982171a8d4af491306abf35cf47cfcce59376b2558979

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
